# Generated by Django 4.1.4 on 2022-12-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Age', models.BinaryField()),
                ('CellNo', models.BinaryField()),
                ('Email', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=25)),
                ('PetName', models.CharField(max_length=25)),
                ('Address', models.TextField()),
            ],
        ),
    ]
